import Head from "next/head";
import { Box, Text, Flex, Image, Divider } from "@chakra-ui/react";
import SectionOne from "@/components/SectionOne";
import CardContainer from "@/components/CardContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Orchard FED test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionOne />
      <CardContainer title="all the latest from aeg" />
    </>
  );
}
